#!/bin/bash
# DO NOT MODIFY THIS FILE DIRECTLY - CREATE A COPY OF IT IN A DIRECTORY NOT BEING UNDER VERSION CONTROL!

export BASE_PATH="$HOME/Projects"
export PROJECT_NAME="hackathon"
export PROJECT_REPO="spring-boot-starter"
export PROJECT_PATH="$BASE_PATH/$PROJECT_NAME"
export PROJECT_REPO_PATH="$PROJECT_PATH/$PROJECT_REPO"
export INTERNAL_NEXUS_PASSWORD=""
export ADD_BASH_SCRIPT="$PROJECT_REPO_PATH/etc/shell/additional_bash_profile.sh"

/bin/bash -l -i